// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Affecto.IdentityManagement.Store.EntityFramework.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserCustomPropertiesAndPassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCustomPropertiesAndPassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201510011322598_UserCustomPropertiesAndPassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
