// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Affecto.IdentityManagement.Store.EntityFramework.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ExternalGroupNameAddedForGroupAndRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExternalGroupNameAddedForGroupAndRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201502171255064_ExternalGroupNameAddedForGroupAndRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
