// <auto-generated />
namespace Affecto.IdentityManagement.Store.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrganizationEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrganizationEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201601221145502_OrganizationEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
