// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Affecto.IdentityManagement.Store.PostgreSql.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PasswordAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PasswordAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201510011324016_PasswordAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
